### ISSUE TITLE
Conserve originating input file paths in URLs

### ISSUE THREAD

**Issue by jro1234** [jrossyra/adaptivemd#10]
When specifying input files, save the source file paths if the files are not loaded into the database so rp can copy them using this path. maybe save these paths even if they are loaded into the database.
- [x] add source filepath attribute to File object
- [x] make sure this inserts to database

**Comment by jrossyra** [comment]
- [ ] add source filepath attribute to File object
- [ ] make sure this inserts to database

**Comment by jro1234** [comment]
These are saved in the file object already, just use generator to locate the input files, find corresponding file documents, and read source path from there.
